sudo: false
language: go
go:
- 1.6
install:
  - go version
  - rrdtool --version
script: make all coverage
before_install:
  - pip install --user codecov>=1.6.5
after_success:
  - codecov
addons:
  apt:
    packages:
      - rrdtool
